### ISSUE TITLE
OSM: Juju models are not cleaned up when removing NS instance

### ISSUE THREAD

**Issue by dreibh** [charmed-osm/layer-sshproxy#9]
I am not sure whether this issue is caused by layer-sshproxy or another part of OSM.

When making some tests with creating and removing NSs with VNFs using Charms, I noticed that at least sometimes the Juju models do not get cleaned up:
```
$ juju list-models
Controller: osm

Model                                  Cloud/Region         Type  Status     Machines  Units  Access  Last connection
5308bf0e-15e6-4398-b6fa-a1254ef0f9a5   localhost/localhost  lxd   available         1      1  admin   3 hours ago
5e23b013-4d48-4771-966c-e9e72efdbef5   localhost/localhost  lxd   available         2      2  admin   3 hours ago
82fdfb47-d5c9-4281-a0c3-783e4259ba54*  localhost/localhost  lxd   available         4      4  admin   5 seconds ago
cf15deb2-7b15-4fb4-80b0-f6c026565151   localhost/localhost  lxd   available         2      2  admin   27 seconds ago
controller                             localhost/localhost  lxd   available         1      -  admin   just now
d39d59de-90ec-49af-99f7-1100e7bdf7e1   localhost/localhost  lxd   available         2      2  admin   2 hours ago
default                                localhost/localhost  lxd   available         0      -  admin   2020-03-04
```
The setup here is just running one NS with one VNF instance, but the old Juju models created for already-deleted NS/VNF instances seem to not get disposed. Tested with OSM ReleaseSEVEN.

**Comment by AdamIsrael** [comment]
It's unrelated to sshproxy, but it might be related to [bug 969](https://osm.etsi.org/bugzilla/show_bug.cgi?id=969). Please comment there if that's relevant to you, or file a [new](https://osm.etsi.org/bugzilla/enter_bug.cgi) bug if not.

Thanks!
